export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const CART_PRODUCTS = "CART_PRODUCTS";
export const CART_CHECKOUT = "CART_CHECKOUTS";
export const CART_PRODUCT_REMOVER = "CART_PRODUCT_REMOVER";
